[package]
name = "log-viewier2"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23"
egui = "0.23"
egui_extras = "0.23"
notify = "5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.9"
chrono = "0.4"
rfd = "0.11"

